"""Add interview completion tracking columns

Revision ID: 22e5302dbcba
Revises: 002
Create Date: 2026-02-20 14:13:42.946132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e5302dbcba'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('phone_screen_completed', sa.Boolean(), nullable=True, default=False))
    op.add_column('job_applications', sa.Column('phone_screen_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_applications', sa.Column('assessment_completed', sa.Boolean(), nullable=True, default=False))
    op.add_column('job_applications', sa.Column('assessment_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_applications', sa.Column('technical_completed', sa.Boolean(), nullable=True, default=False))
    op.add_column('job_applications', sa.Column('technical_completed_at', sa.DateTime(timezone=True), nullable=True))
    
    # Update existing rows to have default False values
    op.execute("UPDATE job_applications SET phone_screen_completed = false WHERE phone_screen_completed IS NULL")
    op.execute("UPDATE job_applications SET assessment_completed = false WHERE assessment_completed IS NULL")
    op.execute("UPDATE job_applications SET technical_completed = false WHERE technical_completed IS NULL")
    
    # Now make the columns NOT NULL
    op.alter_column('job_applications', 'phone_screen_completed', nullable=False)
    op.alter_column('job_applications', 'assessment_completed', nullable=False)
    op.alter_column('job_applications', 'technical_completed', nullable=False)
    
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('job_applications', 'technical_completed_at')
    op.drop_column('job_applications', 'technical_completed')
    op.drop_column('job_applications', 'assessment_completed_at')
    op.drop_column('job_applications', 'assessment_completed')
    op.drop_column('job_applications', 'phone_screen_completed_at')
    op.drop_column('job_applications', 'phone_screen_completed')
    # ### end Alembic commands ###
