"""Add interview stage scheduling columns

Revision ID: d4ec588369c4
Revises: 22e5302dbcba
Create Date: 2026-02-20 14:53:25.834173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ec588369c4'
down_revision = '22e5302dbcba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('phone_screen_scheduled', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_applications', sa.Column('assessment_scheduled', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_applications', sa.Column('technical_scheduled', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'technical_scheduled')
    op.drop_column('job_applications', 'assessment_scheduled')
    op.drop_column('job_applications', 'phone_screen_scheduled')
    # ### end Alembic commands ###
